services:
  db:
    extends:
      file: docker-compose.yml
      service: db
    container_name: solus_dev
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
