name: Create env file

runs:
  using: "composite"
  steps:
    - name: Generate env file
      shell: bash
      run: |
        cat <<EOF > .env.prod
        NODE_ENV=production
        DATABASE_PORT=${{ secrets.DATABASE_PORT }}
        DATABASE_HOST=${{ secrets.DATABASE_HOST }}
        DATABASE_NAME=${{ secrets.DATABASE_NAME }}
        DATABASE_USER=${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
        DATABASE_URL=${{ secrets.DATABASE_URL }}
        SERVER_PORT=${{ vars.SERVER_PORT }}
        SERVER_JWT_SECRET=${{ secrets.SERVER_JWT_SECRET }}
        BUCKET_NAME=${{ vars.BUCKET_NAME }}
        BUCKET_REGION=${{ vars.BUCKET_REGION }}
        BUCKET_ACCESS_KEY=${{ secrets.BUCKET_ACCESS_KEY }}
        BUCKET_SECRET_ACCESS_KEY=${{ secrets.BUCKET_SECRET_ACCESS_KEY }}
        EOF
