name: Pull request checks

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/setup-node-dependencies.yml

      - name: Check formatting
        run: yarn app::format:check

      - name: Build applications
        run: yarn app::build

      - name: Run tests
        run: yarn app::test
